version: '2'

services:
  # database:
  #   network_mode: "host"
  #   build: ./mysql
  #   image: db
  #   container_name: database
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  frontend:
    # networks:
    #     - app-tier
    network_mode: "host"
    build: ./client
    image: client
    container_name: client
    volumes:
      - ./client/src:/home/front/app/src
      - ./client/public:/home/front/app/public
      - ./client/.env:/home/front/app/.env
    ports:
      - "8081:8081"
  backend:
    restart: unless-stopped
    network_mode: "host"
    build: ./server
    image: server
    container_name: server
    volumes:
      - ./server/app:/home/server/app
      - ./server/.env:/home/server/.env
      - ./server/server.js:/home/server/server.js
    ports:
      - "8080:8080"
    # depends_on:
    #   - database
  nginx:
    network_mode: "host"
    build: ./nginx
    image: proxy_server
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8888:8888"
