version: '2'

services:
  # database:
  #   network_mode: "host"
  #   build: ./mysql
  #   image: db
  #   container_name: database
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root

  # frontend:

  #   network_mode: "host"
  #   build: ./client
  #   image: client
  #   container_name: client
  #   volumes:
  #     - ./client/src:/home/front/app/src:ro
  #     - ./client/public:/home/front/app/public:ro
  #     - ./client/build:/home/front/app/build:rw
  #     - ./client/.env:/home/front/app/.env:ro
  #     - ./client/package.json:/home/front/app/package.json:rw
  #     - ./client/package-lock.json:/home/front/app/package-lock.json:rw
  #   ports:
  #     - "8081:8081"
      
  backend:
    restart: unless-stopped
    network_mode: "host"
    build: ./server
    image: server
    container_name: server
    volumes:
      - ./server/app:/home/server/app:ro
      - ./server/.env:/home/server/.env:ro
      - ./server/server.js:/home/server/server.js:ro
      - ./server/package.json:/home/server/package.json:rw
      - ./server/package-lock.json:/home/server/package-lock.json:rw
    ports:
      - "8080:8080"

  nginx:
    network_mode: "host"
    build: ./nginx
    image: proxy_server
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:81"
      - "8081:8081"
      - "8000:8000"
