version: '2'

# networks:
#   app-tier:
#     driver: host

services:
  database:
    # networks:
    #   - app-tier
    network_mode: "host"
    build: ./mysql
    image: database
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  frontend:
    # networks:
    #     - app-tier
    network_mode: "host"
    build: ./client
    image: client
    container_name: client
    volumes:
      - ./client:/home/front/app
    ports:
      - "8081:8081"
  backend:
    # networks:
    #   - app-tier
    restart: unless-stopped
    network_mode: "host"
    build: ./server
    image: server
    container_name: server
    volumes:
      - ./server:/home/server/app
    ports:
      - "8080:8080"
    depends_on:
      - database
  nginx:
    # networks:
    #   - app-tier
    network_mode: "host"
    build: ./nginx
    image: proxy_server
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  